[proxmox]
host = 192.168.2.3
#host = 172.16.5.1
port = 8006

[auth]
username = vdi1@pve
password = your_password_here

[vm]
node = pve
vmid = 0

[connection]
verify_tls = false
timeout = 10

[spice]
proxy_scheme = http
proxy_host = 192.168.2.3
#proxy_host = 172.16.5.1
proxy_port = 3128

[viewer]
fullscreen = true
remote_viewer_path = C:\Program Files\VirtViewer v11.0-256\bin\remote-viewer.exe
#remote_viewer_path = /usr/bin/remote-viewer

[output]
output_dir = .